[general]
import = ["/home/orlando/.config/alacritty/themes/gruvbox_dark.toml"]

[env]
TERM = "alacritty"

[window]
opacity = 1 

[cursor]
style = {shape = "Block", blinking = "always"}
unfocused_hollow = true

[font]
size = 15 

[font.normal]
family = "Roboto Mono"
style = "Medium"
