set -g prefix C-x
unbind C-b
bind-key -T root C-x send-prefix

set -g mode-keys emacs
set -g status-keys emacs
set-option -a terminal-features 'xterm-256color:RGB'

set -g status-style 'bg=#1818b2 fg=#e4e4ef'

set -g pane-border-lines simple
set -g pane-border-indicators arrows
set -g pane-active-border-style "fg=#1818b2"

bind-key -r i run-shell "tmux neww nani"
bind-key -r f run-shell "tmux neww tmux-sessionizer"
bind-key -T copy-mode-emacs C-@ send -X begin-selection
bind-key -T copy-mode-emacs M-w send -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-emacs C-w send -X copy-selection-and-cancel
set-option -sg escape-time 10
set-option -g focus-events on

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
